### ISSUE TITLE
Do you have any example of running this in browser? 

### ISSUE THREAD

**Issue by stgolem** [ltearno/blockchain-js#1]
I am not sure if this is what you intended to do. But i want to run demo app for fun with your blockchain.
The setup i'm looking for is like "many browsers" + "some server nodes".

I'm aware of Nimiq project. But cannot build their nodes: see nimiq-network/core issue 294.

If you have working example i need it asap. Friday evening is my deadline here. Thanks!

**Comment by ltearno** [comment]
This is indeed intended, but not yet implemented. I have the idea to use WebRTC to be able to create a p2p network of browsers. So at the end micing nodejs and brower nodes will be completely normal.

Meanwhile and since you have a so short deadline, here is a plan for you which is kind of quick and dirty. This plan has some limitations but should do for a demo :
- browser nodes will be only client nodes (meaning no other nodes can connect to them)
- this is conditionned to the fact that the code I wrote is compatible with the browser network api (http and websocket queries). I remember having choosen a library for making networking based on that criteria.
- the other thing is I think there are places in the code which use express-js and won't obviously don't work on the browser, you will have to remove them !

- remove the "express" part in the node-network.ts file,
- create a blockchain-browser.ts file with the main code for the browser (only implementing a blockchain client for the moment). You can use blockchain-ws.ts as an example
- use NodeClient in node-network.ts to connect to a remote node
=> this should almost work on browsers directly

I must go now, good luck ;)

**Comment by stgolem** [comment]
Thanks a lot for quick answer! I'll do my best with this plan. 
Will report here of results.

**Comment by stgolem** [comment]
Ok, here are some of my results.
I've removed all of `express` code. I had to use `broserify`, as there is lack of `crypto` package in browser. Also i removed package `ws` as it is poorly implemented api in browser. Instead i used native `WebSocket` that is avaliable in modern browsers.

Hardest part was to complete that blockchain logic. I am currently in progress of some rewrite of it. But here is what i've already tried.

1. Full miner on the browser side
    - we have to connect to 2 other nodes here (server nodes)
    - if we create new block inside browser - there is no simple way to translate that node to server nodes (`registerBlock` method here is not working)
    - that tricky websockets is hard to manage
2. Browser is only a client without mining functions (i am now at this point of rewrite)
    - we only consume blockchain inside browser
    - if we need some changes - we send them to server node with POST to '/lists/:branch'
    - then we just wait in browser when our tx is confirmed

As a concept i was able to show some working thing thanks to you code!

In future i plan to finish some mvp product for our internal usecase. And maybe i will push a PR with that back to you. Thanks!

**Comment by ltearno** [comment]
I need to demo that soon too, so i am also working on running the node on browser now ;)
I will let you know my results : trick is to give away with the rest interface, everything goes through the websocket so that server nodes can push and ask info from browser nodes...

**Comment by ltearno** [comment]
Some news if you want to try : the browser implementation is ready and works on the 'dev' branch of this repo.
Blockchain nodes running on NodeJs and browser are completely identical.
Every communication goes through WebSocket, so I might completely remove the REST surface (maybe not because it's easier to test with Postman ;) )
So when a websocket is established it allows the two nodes at both sides to communicate in either way, that's very cool.

I splitted the project in two (core and angular ui). The README in the root directory contains instructions to launch nodejs + browser tabs, you might be interested trying that.

Here is what worked so far :

- launch a NodeJs node
- launch two browser tabs
- mine some blocks, all nodes are updated
- kill the NodeJs node and one browser tab => now only one browser tabs is alive and that is the only node to be alive with our freshly mined blocks.
- launch a NodeJs node
- launch a browser tab
- connect the new browser tab to the nodejs node
- connect the old browser tab to the nodejs => nodejs node receives all informations from old browser tab. The new browser tab receives all informations from the nodejs node
- all nodes are now synced on the same data !!!

Really cool!
